import { MigrationInterface, QueryRunner } from "typeorm";

export class InitVuelosSchema1791167576852 implements MigrationInterface {
    name = 'InitVuelosSchema1791167576852'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // `synchronize` installs this extension on its own; a migration must do it explicitly (uuid primary keys).
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TABLE "vuelos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "aerolinea" character varying(150) NOT NULL, "codigoAerolinea" character varying(2) NOT NULL, "codigoVuelo" character varying(20) NOT NULL, "origenIATA" character(3) NOT NULL, "destinoIATA" character(3) NOT NULL, "fechaSalida" TIMESTAMP WITH TIME ZONE NOT NULL, "fechaLlegada" TIMESTAMP WITH TIME ZONE NOT NULL, "precioBase" numeric(10,2) NOT NULL, "asientosDisponibles" integer NOT NULL, "capacidadTotal" integer NOT NULL DEFAULT '180', "durationMinutes" integer NOT NULL, CONSTRAINT "UQ_vuelos_codigo_salida" UNIQUE ("codigoVuelo", "fechaSalida"), CONSTRAINT "CHK_vuelos_asientos" CHECK ("asientosDisponibles" >= 0 AND "asientosDisponibles" <= "capacidadTotal"), CONSTRAINT "CHK_vuelos_origen_distinto" CHECK ("origenIATA" <> "destinoIATA"), CONSTRAINT "CHK_vuelos_iata_formato" CHECK ("origenIATA" ~ '^[A-Z]{3}$' AND "destinoIATA" ~ '^[A-Z]{3}$'), CONSTRAINT "PK_f4e1ec4253ec27fa0253b7c6a1a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_vuelos_ruta_salida" ON "vuelos" ("origenIATA", "destinoIATA", "fechaSalida") `);
        await queryRunner.query(`CREATE TABLE "vuelos_tickets" ("ticketId" uuid NOT NULL DEFAULT uuid_generate_v4(), "bookingId" uuid NOT NULL, "passengerId" uuid NOT NULL, "eTicketNumber" character varying(13) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'ISSUED', "issuedAt" TIMESTAMP NOT NULL, CONSTRAINT "UQ_651a1d31793af007b706dc1e70b" UNIQUE ("eTicketNumber"), CONSTRAINT "PK_459bf33701e8e58e33f67333fdc" PRIMARY KEY ("ticketId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_vuelos_tickets_booking" ON "vuelos_tickets" ("bookingId") `);
        await queryRunner.query(`CREATE TABLE "vuelos_seat_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vueloId" uuid NOT NULL, "seatNumber" character varying(4) NOT NULL, "bookingId" uuid NOT NULL, "passengerId" uuid NOT NULL, CONSTRAINT "UQ_vuelos_seat_vuelo_numero" UNIQUE ("vueloId", "seatNumber"), CONSTRAINT "PK_ab82d690879685d44d7d3d11a7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vuelos_passengers" ("passengerId" uuid NOT NULL DEFAULT uuid_generate_v4(), "bookingId" uuid NOT NULL, "clientPassengerId" character varying(100) NOT NULL, "associatedAdultClientId" character varying(100), "passengerType" character varying(10) NOT NULL, "firstName" character varying(100) NOT NULL, "lastName" character varying(100) NOT NULL, "documentType" character varying(20) NOT NULL, "documentNumber" character varying(50) NOT NULL, "nationality" character varying(2) NOT NULL, "birthDate" date NOT NULL, "gender" character varying(1) NOT NULL, "contactEmail" character varying(150) NOT NULL, "contactPhone" character varying(30) NOT NULL, CONSTRAINT "PK_435372adbba10927c92d81caa69" PRIMARY KEY ("passengerId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_vuelos_passengers_booking" ON "vuelos_passengers" ("bookingId") `);
        await queryRunner.query(`CREATE TABLE "vuelos_idempotency_records" ("idempotencyKey" character varying(100) NOT NULL, "route" character varying(100) NOT NULL, "ownerId" character varying(100) NOT NULL, "requestHash" character(64) NOT NULL, "state" character varying(12) NOT NULL DEFAULT 'IN_PROGRESS', "responseStatus" integer, "responseBody" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b9a6210e86238c2ad78cd4f5a42" PRIMARY KEY ("idempotencyKey", "route", "ownerId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_vuelos_idempotency_created" ON "vuelos_idempotency_records" ("createdAt") `);
        await queryRunner.query(`CREATE TABLE "vuelos_flight_offers" ("offerId" uuid NOT NULL DEFAULT uuid_generate_v4(), "itineraries" jsonb NOT NULL, "grandTotal" character varying(20) NOT NULL, "currency" character varying(3) NOT NULL, "passengersBreakdown" jsonb NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "expiresAt" TIMESTAMP NOT NULL, CONSTRAINT "PK_b201debc294100d2c4ac8c5193c" PRIMARY KEY ("offerId"))`);
        await queryRunner.query(`CREATE TABLE "vuelos_flight_holds" ("holdId" uuid NOT NULL DEFAULT uuid_generate_v4(), "offerId" uuid NOT NULL, "ownerId" character varying(100) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'HELD', "lockedPrice" character varying(20) NOT NULL, "currency" character varying(3) NOT NULL, "ttlMinutes" integer NOT NULL, "itinerarySelections" jsonb NOT NULL, "passengersBreakdown" jsonb NOT NULL, "inventory" jsonb NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "expiresAt" TIMESTAMP NOT NULL, CONSTRAINT "PK_26dbfcb86aec01776b1063373a9" PRIMARY KEY ("holdId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_vuelos_holds_status_expires" ON "vuelos_flight_holds" ("status", "expiresAt") `);
        await queryRunner.query(`CREATE TABLE "vuelos_fare_families" ("code" character varying(20) NOT NULL, "name" character varying(100) NOT NULL, "carryOnKg" integer NOT NULL, "checkedBags" integer NOT NULL, "changeable" boolean NOT NULL, "refundable" boolean NOT NULL, "seatSelectionIncluded" boolean NOT NULL, "upgradeEligible" boolean NOT NULL, "accrualFactor" double precision NOT NULL, "priceMultiplier" double precision NOT NULL, CONSTRAINT "PK_686bbbccba21e887051886e7a7a" PRIMARY KEY ("code"))`);
        await queryRunner.query(`CREATE TABLE "vuelos_bookings" ("bookingId" uuid NOT NULL DEFAULT uuid_generate_v4(), "pnr" character varying(6) NOT NULL, "holdId" uuid NOT NULL, "status" character varying(30) NOT NULL DEFAULT 'PENDING', "ownerId" character varying(100) NOT NULL, "grandTotal" character varying(20) NOT NULL, "currency" character varying(3) NOT NULL, "paymentReference" character varying(100) NOT NULL, "origin" character(3) NOT NULL, "destination" character(3) NOT NULL, "departureAt" TIMESTAMP WITH TIME ZONE NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT now(), CONSTRAINT "UQ_95b0267b3fa60d0b37e2998a050" UNIQUE ("pnr"), CONSTRAINT "UQ_06aafb7c3a77a2d3bc3840376d1" UNIQUE ("paymentReference"), CONSTRAINT "PK_3bbdd08ac0995dbd91c9cf4b705" PRIMARY KEY ("bookingId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_vuelos_bookings_owner_created" ON "vuelos_bookings" ("ownerId", "createdAt", "bookingId") `);
        await queryRunner.query(`CREATE TABLE "ecom_pagos" ("pagoId" uuid NOT NULL DEFAULT uuid_generate_v4(), "ofertaId" uuid NOT NULL, "ordenId" uuid, "ownerId" character varying(100) NOT NULL, "mercado" character varying(5) NOT NULL, "moneda" character(3) NOT NULL, "montoMinor" bigint NOT NULL, "medio" jsonb NOT NULL, "cuotas" integer NOT NULL DEFAULT '1', "estado" character varying(25) NOT NULL DEFAULT 'PENDIENTE', "autorizacionRef" character varying(100), "codigoRechazo" character varying(50), "antifraude" jsonb, "claveIdempotencia" character varying(100) NOT NULL, "creadoEn" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizadoEn" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_3c8e0abe050063acf45f6ca6c44" PRIMARY KEY ("pagoId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ecom_pagos_oferta" ON "ecom_pagos" ("ofertaId", "creadoEn") `);
        await queryRunner.query(`CREATE TABLE "ecom_ordenes" ("ordenId" uuid NOT NULL DEFAULT uuid_generate_v4(), "numeroOrden" character varying(20) NOT NULL, "ofertaId" uuid NOT NULL, "ownerId" character varying(100) NOT NULL, "clienteId" uuid, "mercado" character varying(5) NOT NULL, "moneda" character(3) NOT NULL, "totalMinor" bigint NOT NULL, "estado" character varying(25) NOT NULL, "canal" character varying(10) NOT NULL DEFAULT 'WEB', "pago" jsonb NOT NULL, "pnr" character(6), "bookingId" uuid, "trayectos" jsonb NOT NULL, "pasajeros" text NOT NULL, "contacto" text NOT NULL, "facturacion" text NOT NULL, "condicionesAceptadas" jsonb NOT NULL, "historial" jsonb NOT NULL, "creadaEn" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT now(), "actualizadaEn" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_0ed6bc9b11179e735e0ce960c43" PRIMARY KEY ("ordenId"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_ecom_ordenes_oferta_activa" ON "ecom_ordenes" ("ofertaId") WHERE "estado" <> 'FALLIDA_COMPENSADA'`);
        await queryRunner.query(`CREATE INDEX "IDX_ecom_ordenes_owner_created" ON "ecom_ordenes" ("ownerId", "creadaEn", "ordenId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ecom_ordenes_pnr" ON "ecom_ordenes" ("pnr") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_ecom_ordenes_numero" ON "ecom_ordenes" ("numeroOrden") `);
        await queryRunner.query(`CREATE TABLE "ecom_ofertas" ("ofertaId" uuid NOT NULL DEFAULT uuid_generate_v4(), "mercado" character varying(5) NOT NULL, "moneda" character(3) NOT NULL, "ownerId" character varying(100) NOT NULL, "estado" character varying(20) NOT NULL DEFAULT 'ABIERTA', "trayectos" jsonb NOT NULL, "composicion" jsonb NOT NULL, "totalMinor" bigint NOT NULL, "totalPropuestoMinor" bigint, "gdsOfferId" uuid NOT NULL, "holdId" uuid NOT NULL, "venceEn" TIMESTAMP WITH TIME ZONE NOT NULL, "datosPasajeros" text, "facturacion" text, "condicionesAceptadas" jsonb, "revalidadaEn" TIMESTAMP WITH TIME ZONE, "enPagoDesde" TIMESTAMP WITH TIME ZONE, "creadaEn" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizadaEn" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_0a536e611cc7ace315a3c2d0901" PRIMARY KEY ("ofertaId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ecom_ofertas_hold" ON "ecom_ofertas" ("holdId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ecom_ofertas_owner" ON "ecom_ofertas" ("ownerId", "creadaEn") `);
        await queryRunner.query(`CREATE TABLE "ecom_plantillas_notificacion" ("plantillaId" uuid NOT NULL DEFAULT uuid_generate_v4(), "tipo" character varying(30) NOT NULL, "mercado" character varying(5), "idioma" character varying(5) NOT NULL, "version" integer NOT NULL, "asunto" character varying(200) NOT NULL, "cuerpo" text NOT NULL, "activa" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_ecom_plantillas" UNIQUE ("tipo", "mercado", "idioma", "version"), CONSTRAINT "PK_331dd4e1eee6421a15b6f32736d" PRIMARY KEY ("plantillaId"))`);
        await queryRunner.query(`CREATE TABLE "ecom_notificaciones" ("notificacionId" uuid NOT NULL DEFAULT uuid_generate_v4(), "eventoId" uuid NOT NULL, "tipo" character varying(30) NOT NULL, "canal" character varying(12) NOT NULL, "destinatario" character varying(150) NOT NULL, "mercado" character varying(5), "idioma" character varying(5) NOT NULL, "plantillaVersion" integer NOT NULL, "asunto" character varying(200) NOT NULL, "cuerpo" text NOT NULL, "referencia" character varying(100) NOT NULL, "estado" character varying(10) NOT NULL, "intentos" integer NOT NULL DEFAULT '0', "error" character varying(300), "creadoEn" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_4b1456297573edae92a513906af" PRIMARY KEY ("notificacionId"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_ecom_notificaciones_evento" ON "ecom_notificaciones" ("eventoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ecom_notificaciones_referencia" ON "ecom_notificaciones" ("referencia", "creadoEn") `);
        await queryRunner.query(`CREATE TABLE "ecom_mercados" ("codigo" character varying(5) NOT NULL, "pais" character(2) NOT NULL, "nombre" character varying(100) NOT NULL, "idiomas" text array NOT NULL, "idiomaPorDefecto" character varying(5) NOT NULL, "moneda" character(3) NOT NULL, "tipoCambioDesdeUsd" numeric(14,6) NOT NULL, "productosBuscador" text array NOT NULL, "mediosPago" jsonb NOT NULL, "reglasRegulatorias" jsonb NOT NULL, "textosLegales" jsonb NOT NULL, "identificacionesFiscales" jsonb NOT NULL, "activo" boolean NOT NULL DEFAULT true, "version" integer NOT NULL DEFAULT '1', "actualizadoEn" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_97ef3cca280f8f75605d6d38931" PRIMARY KEY ("codigo"))`);
        await queryRunner.query(`CREATE TABLE "ecom_auditoria_cambios" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entidad" character varying(50) NOT NULL, "entidadId" character varying(100) NOT NULL, "actorId" character varying(100) NOT NULL, "accion" character varying(30) NOT NULL, "antes" jsonb NOT NULL, "despues" jsonb NOT NULL, "creadoEn" TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d4a8d1ee5460b994bec5164aae5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ecom_auditoria_entidad" ON "ecom_auditoria_cambios" ("entidad", "entidadId", "creadoEn") `);
        await queryRunner.query(`CREATE TABLE "ecom_clientes" ("clienteId" uuid NOT NULL DEFAULT uuid_generate_v4(), "correo" character varying(150) NOT NULL, "correoVerificado" boolean NOT NULL DEFAULT false, "hashContrasena" character varying(300) NOT NULL, "nombres" character varying(100) NOT NULL, "apellidos" character varying(100) NOT NULL, "fechaNacimiento" date NOT NULL, "telefono" character varying(30), "numeroSocio" character varying(20) NOT NULL, "mercadoPreferido" character varying(5) NOT NULL, "idiomaPreferido" character varying(5) NOT NULL, "canalNotificacion" character varying(12) NOT NULL DEFAULT 'EMAIL', "consentimientoMarketing" boolean NOT NULL DEFAULT false, "terminosVersionAceptada" character varying(20) NOT NULL, "terminosAceptadosEn" TIMESTAMP WITH TIME ZONE NOT NULL, "roles" text array NOT NULL, "intentosFallidos" integer NOT NULL DEFAULT '0', "bloqueadoHasta" TIMESTAMP WITH TIME ZONE, "tokenVerificacionHash" character(64), "tokenVerificacionVenceEn" TIMESTAMP WITH TIME ZONE, "creadoEn" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actualizadoEn" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_66a7585676f3f887fe05f8a9cec" PRIMARY KEY ("clienteId"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_ecom_clientes_correo" ON "ecom_clientes" ("correo") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_ecom_clientes_socio" ON "ecom_clientes" ("numeroSocio") `);
        await queryRunner.query(`CREATE TABLE "ecom_localidades" ("iata" character(3) NOT NULL, "ciudad" character varying(100) NOT NULL, "nombre" character varying(150) NOT NULL, "pais" character(2) NOT NULL, "paisNombre" character varying(100) NOT NULL, "zonaHoraria" character varying(50) NOT NULL, "ciudadNorm" character varying(100) NOT NULL, "nombreNorm" character varying(150) NOT NULL, CONSTRAINT "PK_f8977adf132d583d5c4857ed20b" PRIMARY KEY ("iata"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ecom_localidades_ciudad_norm" ON "ecom_localidades" ("ciudadNorm") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_ecom_localidades_ciudad_norm"`);
        await queryRunner.query(`DROP TABLE "ecom_localidades"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_ecom_clientes_socio"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_ecom_clientes_correo"`);
        await queryRunner.query(`DROP TABLE "ecom_clientes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ecom_auditoria_entidad"`);
        await queryRunner.query(`DROP TABLE "ecom_auditoria_cambios"`);
        await queryRunner.query(`DROP TABLE "ecom_mercados"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ecom_notificaciones_referencia"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_ecom_notificaciones_evento"`);
        await queryRunner.query(`DROP TABLE "ecom_notificaciones"`);
        await queryRunner.query(`DROP TABLE "ecom_plantillas_notificacion"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ecom_ofertas_owner"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ecom_ofertas_hold"`);
        await queryRunner.query(`DROP TABLE "ecom_ofertas"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_ecom_ordenes_numero"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ecom_ordenes_pnr"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ecom_ordenes_owner_created"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_ecom_ordenes_oferta_activa"`);
        await queryRunner.query(`DROP TABLE "ecom_ordenes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ecom_pagos_oferta"`);
        await queryRunner.query(`DROP TABLE "ecom_pagos"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vuelos_bookings_owner_created"`);
        await queryRunner.query(`DROP TABLE "vuelos_bookings"`);
        await queryRunner.query(`DROP TABLE "vuelos_fare_families"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vuelos_holds_status_expires"`);
        await queryRunner.query(`DROP TABLE "vuelos_flight_holds"`);
        await queryRunner.query(`DROP TABLE "vuelos_flight_offers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vuelos_idempotency_created"`);
        await queryRunner.query(`DROP TABLE "vuelos_idempotency_records"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vuelos_passengers_booking"`);
        await queryRunner.query(`DROP TABLE "vuelos_passengers"`);
        await queryRunner.query(`DROP TABLE "vuelos_seat_assignments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vuelos_tickets_booking"`);
        await queryRunner.query(`DROP TABLE "vuelos_tickets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_vuelos_ruta_salida"`);
        await queryRunner.query(`DROP TABLE "vuelos"`);
    }

}
