import { Column, Entity, Index, PrimaryGeneratedColumn } from 'typeorm';
import { encryptedJson } from '../common/cifrado';

export type PassengerType = 'ADULT' | 'YOUTH' | 'CHILD' | 'INFANT';

/**
 * Identity and contact data of a passenger is encrypted at rest (RNF-18), like the e-commerce
 * order snapshot. It is never queried in SQL: bookings are found by id/PNR, and the duplicate
 * check runs on the request before anything is stored.
 */
@Entity('vuelos_passengers')
@Index('IDX_vuelos_passengers_booking', ['bookingId'])
export class Passenger {
  @PrimaryGeneratedColumn('uuid')
  passengerId: string;

  @Column({ type: 'uuid' })
  bookingId: string;

  // The caller-chosen passengerId from the booking request (seats and infant-adult links
  // refer to it); the primary key above is generated by us.
  @Column({ type: 'varchar', length: 100 })
  clientPassengerId: string;

  @Column({ type: 'varchar', length: 100, nullable: true })
  associatedAdultClientId: string | null;

  @Column({ type: 'varchar', length: 10 })
  passengerType: PassengerType;

  @Column({ type: 'text', transformer: encryptedJson<string>() })
  firstName: string;

  @Column({ type: 'text', transformer: encryptedJson<string>() })
  lastName: string;

  @Column({ type: 'varchar', length: 20 })
  documentType: string;

  @Column({ type: 'text', transformer: encryptedJson<string>() })
  documentNumber: string;

  @Column({ type: 'varchar', length: 2 })
  nationality: string;

  @Column({ type: 'text', transformer: encryptedJson<string>() })
  birthDate: string;

  @Column({ type: 'varchar', length: 1 })
  gender: string;

  @Column({ type: 'text', transformer: encryptedJson<string>() })
  contactEmail: string;

  @Column({ type: 'text', transformer: encryptedJson<string>() })
  contactPhone: string;
}
